version: '3.3'
services:
  login:
    image: ggabriell455/palindromos:1.1
    container_name: palindromos-app
    restart: always
    environment:
      DB_URL_CONNECTION: jdbc:h2:mem:palindrome;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
      DB_USER_NAME: 'sa'
      DB_PASSWORD: 'password'
      SERVER_PORT: '8080'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,address=*:5005,server=y,suspend=n"
    ports:
      - '8080:8080'
      - '5005:5005'
    expose:
      - '8080'
      - '5005'
    networks:
      - local-loqin
networks:
  local-loqin:
    driver: bridge
